# -*- coding: utf-8 -*-
"""foo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LP5OveAPZnCAymzY81vzbqdiYo8JOC9G
"""

def betaSatu():
  	print("betaSatu")

def betaDua():
  	print("betaDua")

