# -*- coding: utf-8 -*-
"""main_arya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BYNlOsXQPw5q5kG2EpFlCcGmfKXys-7I
"""

def greet(name):
    return f"Hello, {name}"

pi = 3.14159265359

def square(x):
    return x**2