# -*- coding: utf-8 -*-
"""main_arya_run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n8Gj6kiM2CFknQfgfEqge-jXAYubZG8g
"""

import main_arya

message = main_arya.greet("Arya")
print(message)

radius = 5
area = main_arya.pi * (radius**2)
print(f"Luas lingkaran dengan radius {radius} adalah {area:2f}")